"""empty message

Revision ID: 0de1bd544120
Revises: f7a065306b83
Create Date: 2021-02-16 10:38:57.924806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de1bd544120'
down_revision = 'f7a065306b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pirep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_time', sa.DateTime(), nullable=True),
    sa.Column('observation_time', sa.DateTime(), nullable=True),
    sa.Column('mid_point_assumed', sa.Boolean(), nullable=True),
    sa.Column('no_time_stamp', sa.Boolean(), nullable=True),
    sa.Column('flt_lvl_range', sa.Boolean(), nullable=True),
    sa.Column('above_ground_level_indicated', sa.Boolean(), nullable=True),
    sa.Column('no_flt_lvl', sa.Boolean(), nullable=True),
    sa.Column('bad_location', sa.Boolean(), nullable=True),
    sa.Column('aircraft_ref', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_ft_msl', sa.Integer(), nullable=True),
    sa.Column('sky_cover1', sa.String(length=10), nullable=True),
    sa.Column('sky_cover2', sa.String(length=10), nullable=True),
    sa.Column('cloud_base_ft_msl1', sa.Integer(), nullable=True),
    sa.Column('cloud_base_ft_msl2', sa.Integer(), nullable=True),
    sa.Column('cloud_top_ft_msl1', sa.Integer(), nullable=True),
    sa.Column('cloud_top_ft_msl2', sa.Integer(), nullable=True),
    sa.Column('turbulence_type1', sa.String(length=5), nullable=True),
    sa.Column('turbulence_type2', sa.String(length=5), nullable=True),
    sa.Column('turbulence_intensity1', sa.String(length=10), nullable=True),
    sa.Column('turbulence_intensity2', sa.String(length=10), nullable=True),
    sa.Column('turbulence_base_ft_msl1', sa.Integer(), nullable=True),
    sa.Column('turbulence_base_ft_msl2', sa.Integer(), nullable=True),
    sa.Column('turbulence_top_ft_msl1', sa.Integer(), nullable=True),
    sa.Column('turbulence_top_ft_msl2', sa.Integer(), nullable=True),
    sa.Column('turbulence_freq1', sa.String(length=10), nullable=True),
    sa.Column('turbulence_freq2', sa.String(length=10), nullable=True),
    sa.Column('icing_type1', sa.String(length=10), nullable=True),
    sa.Column('icing_type2', sa.String(length=10), nullable=True),
    sa.Column('icing_intensity1', sa.String(length=10), nullable=True),
    sa.Column('icing_intensity2', sa.String(length=10), nullable=True),
    sa.Column('icing_base_ft_msl1', sa.Integer(), nullable=True),
    sa.Column('icing_base_ft_msl2', sa.Integer(), nullable=True),
    sa.Column('icing_top_ft_msl1', sa.Integer(), nullable=True),
    sa.Column('icing_top_ft_msl2', sa.Integer(), nullable=True),
    sa.Column('visibility_statute_mi', sa.Integer(), nullable=True),
    sa.Column('wx_string', sa.String(length=10), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('wind_dir_degrees', sa.Integer(), nullable=True),
    sa.Column('wind_speed_kt', sa.Integer(), nullable=True),
    sa.Column('vert_gust_kt', sa.Integer(), nullable=True),
    sa.Column('pirep_type', sa.String(length=6), nullable=True),
    sa.Column('raw_text', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pirep_aircraft_ref'), 'pirep', ['aircraft_ref'], unique=False)
    op.create_index(op.f('ix_pirep_latitude'), 'pirep', ['latitude'], unique=False)
    op.create_index(op.f('ix_pirep_longitude'), 'pirep', ['longitude'], unique=False)
    op.create_index(op.f('ix_pirep_observation_time'), 'pirep', ['observation_time'], unique=False)
    op.create_index(op.f('ix_pirep_receipt_time'), 'pirep', ['receipt_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pirep_receipt_time'), table_name='pirep')
    op.drop_index(op.f('ix_pirep_observation_time'), table_name='pirep')
    op.drop_index(op.f('ix_pirep_longitude'), table_name='pirep')
    op.drop_index(op.f('ix_pirep_latitude'), table_name='pirep')
    op.drop_index(op.f('ix_pirep_aircraft_ref'), table_name='pirep')
    op.drop_table('pirep')
    # ### end Alembic commands ###
