"""empty message

Revision ID: 29979c8a6dae
Revises: 76db49a08e5e
Create Date: 2021-02-15 12:20:58.596157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29979c8a6dae'
down_revision = '76db49a08e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('metar_station_id_fkey', 'metar', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('metar_station_id_fkey', 'metar', 'station', ['station_id'], ['station_id'])
    # ### end Alembic commands ###
