"""empty message

Revision ID: baaa55597f73
Revises: 0e17d23bcb1e
Create Date: 2021-02-12 15:54:10.824625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baaa55597f73'
down_revision = '0e17d23bcb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(length=500), nullable=True),
    sa.Column('station_id', sa.String(length=4), nullable=True),
    sa.Column('observation_time', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('dewpoint_c', sa.Float(), nullable=True),
    sa.Column('wind_dir_degrees', sa.Integer(), nullable=True),
    sa.Column('wind_speed_kt', sa.Integer(), nullable=True),
    sa.Column('wind_gust_kt', sa.Integer(), nullable=True),
    sa.Column('visibility_statute_mi', sa.Float(), nullable=True),
    sa.Column('altim_in_hg', sa.Float(), nullable=True),
    sa.Column('sea_level_pressure_mb', sa.Float(), nullable=True),
    sa.Column('corrected', sa.Boolean(), nullable=True),
    sa.Column('auto', sa.Boolean(), nullable=True),
    sa.Column('auto_station', sa.Boolean(), nullable=True),
    sa.Column('maintenance_indicator_on', sa.Boolean(), nullable=True),
    sa.Column('no_signal', sa.Boolean(), nullable=True),
    sa.Column('lightning_sensor_off', sa.Boolean(), nullable=True),
    sa.Column('freezing_rain_sensor_off', sa.Boolean(), nullable=True),
    sa.Column('present_weather_sensor_off', sa.Boolean(), nullable=True),
    sa.Column('wx_string', sa.String(length=10), nullable=True),
    sa.Column('sky_cover1', sa.String(length=10), nullable=True),
    sa.Column('cloud_base_ft_agl1', sa.Integer(), nullable=True),
    sa.Column('sky_cover2', sa.String(length=10), nullable=True),
    sa.Column('cloud_base_ft_agl2', sa.Integer(), nullable=True),
    sa.Column('sky_cover3', sa.String(length=10), nullable=True),
    sa.Column('cloud_base_ft_ag3', sa.Integer(), nullable=True),
    sa.Column('sky_cover4', sa.String(length=10), nullable=True),
    sa.Column('cloud_base_ft_ag4', sa.Integer(), nullable=True),
    sa.Column('flight_category', sa.String(), nullable=True),
    sa.Column('three_hr_pressure_tendency_mb', sa.Float(), nullable=True),
    sa.Column('maxT_c', sa.Float(), nullable=True),
    sa.Column('minT_c', sa.Float(), nullable=True),
    sa.Column('maxT24hr_c', sa.Float(), nullable=True),
    sa.Column('minT24hr_c', sa.Float(), nullable=True),
    sa.Column('precip_in', sa.Float(), nullable=True),
    sa.Column('pcp3hr_in', sa.Float(), nullable=True),
    sa.Column('pcp6hr_in', sa.Float(), nullable=True),
    sa.Column('pcp24hr_in', sa.Float(), nullable=True),
    sa.Column('snow_in', sa.Float(), nullable=True),
    sa.Column('vert_vis_ft', sa.Integer(), nullable=True),
    sa.Column('metar_type', sa.String(length=10), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.station_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metar_station_id'), 'metar', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metar_station_id'), table_name='metar')
    op.drop_table('metar')
    # ### end Alembic commands ###
