"""empty message

Revision ID: ca101e5ea850
Revises: 29979c8a6dae
Create Date: 2021-02-15 15:35:28.459332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca101e5ea850'
down_revision = '29979c8a6dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taf', sa.Column('raw_text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taf', 'raw_text')
    # ### end Alembic commands ###
