"""empty message

Revision ID: f7a065306b83
Revises: ca101e5ea850
Create Date: 2021-02-16 06:47:05.752314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a065306b83'
down_revision = 'ca101e5ea850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taf', sa.Column('cloud_base_ft_agl1', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('cloud_base_ft_agl2', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('cloud_type1', sa.String(length=3), nullable=True))
    op.add_column('taf', sa.Column('cloud_type2', sa.String(length=3), nullable=True))
    op.add_column('taf', sa.Column('icing_intensity1', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('icing_intensity2', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('icing_max_alt_ft_agl1', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('icing_max_alt_ft_agl2', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('icing_min_alt_ft_agl1', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('icing_min_alt_ft_agl2', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('sky_cover1', sa.String(length=3), nullable=True))
    op.add_column('taf', sa.Column('sky_cover2', sa.String(length=3), nullable=True))
    op.add_column('taf', sa.Column('turbulence_intensity1', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('turbulence_intensity2', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('turbulence_max_alt_ft_agl1', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('turbulence_max_alt_ft_agl2', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('turbulence_min_alt_ft_agl1', sa.Integer(), nullable=True))
    op.add_column('taf', sa.Column('turbulence_min_alt_ft_agl2', sa.Integer(), nullable=True))
    op.drop_index('ix_taf_cloud_type', table_name='taf')
    op.drop_index('ix_taf_sky_cover', table_name='taf')
    op.create_index(op.f('ix_taf_cloud_type1'), 'taf', ['cloud_type1'], unique=False)
    op.create_index(op.f('ix_taf_cloud_type2'), 'taf', ['cloud_type2'], unique=False)
    op.create_index(op.f('ix_taf_sky_cover1'), 'taf', ['sky_cover1'], unique=False)
    op.create_index(op.f('ix_taf_sky_cover2'), 'taf', ['sky_cover2'], unique=False)
    op.drop_column('taf', 'icing_min_alt_ft_agl')
    op.drop_column('taf', 'icing_max_alt_ft_agl')
    op.drop_column('taf', 'cloud_type')
    op.drop_column('taf', 'sky_cover')
    op.drop_column('taf', 'icing_intensity')
    op.drop_column('taf', 'turbulence_intensity')
    op.drop_column('taf', 'turbulence_max_alt_ft_agl')
    op.drop_column('taf', 'turbulence_min_alt_ft_agl')
    op.drop_column('taf', 'cloud_base_ft_agl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taf', sa.Column('cloud_base_ft_agl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('taf', sa.Column('turbulence_min_alt_ft_agl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('taf', sa.Column('turbulence_max_alt_ft_agl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('taf', sa.Column('turbulence_intensity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('taf', sa.Column('icing_intensity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('taf', sa.Column('sky_cover', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('taf', sa.Column('cloud_type', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('taf', sa.Column('icing_max_alt_ft_agl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('taf', sa.Column('icing_min_alt_ft_agl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_taf_sky_cover2'), table_name='taf')
    op.drop_index(op.f('ix_taf_sky_cover1'), table_name='taf')
    op.drop_index(op.f('ix_taf_cloud_type2'), table_name='taf')
    op.drop_index(op.f('ix_taf_cloud_type1'), table_name='taf')
    op.create_index('ix_taf_sky_cover', 'taf', ['sky_cover'], unique=False)
    op.create_index('ix_taf_cloud_type', 'taf', ['cloud_type'], unique=False)
    op.drop_column('taf', 'turbulence_min_alt_ft_agl2')
    op.drop_column('taf', 'turbulence_min_alt_ft_agl1')
    op.drop_column('taf', 'turbulence_max_alt_ft_agl2')
    op.drop_column('taf', 'turbulence_max_alt_ft_agl1')
    op.drop_column('taf', 'turbulence_intensity2')
    op.drop_column('taf', 'turbulence_intensity1')
    op.drop_column('taf', 'sky_cover2')
    op.drop_column('taf', 'sky_cover1')
    op.drop_column('taf', 'icing_min_alt_ft_agl2')
    op.drop_column('taf', 'icing_min_alt_ft_agl1')
    op.drop_column('taf', 'icing_max_alt_ft_agl2')
    op.drop_column('taf', 'icing_max_alt_ft_agl1')
    op.drop_column('taf', 'icing_intensity2')
    op.drop_column('taf', 'icing_intensity1')
    op.drop_column('taf', 'cloud_type2')
    op.drop_column('taf', 'cloud_type1')
    op.drop_column('taf', 'cloud_base_ft_agl2')
    op.drop_column('taf', 'cloud_base_ft_agl1')
    # ### end Alembic commands ###
